'use client';
import Link from 'next/link';
import {useEffect,useMemo,useState} from 'react';
import {supabase} from '../lib/supabase';
import {addCartItem,readCart,writeCart} from '../lib/cart';

const fmt=n=>new Intl.NumberFormat('tr-TR',{style:'currency',currency:'TRY',maximumFractionDigits:0}).format(Number(n||0));
export default function StoreClient({releases}){
 const [filter,setFilter]=useState('all'),[formatFilter,setFormatFilter]=useState('all');
 const [cart,setCart]=useState([]),[open,setOpen]=useState(false),[checkout,setCheckout]=useState(false),[busy,setBusy]=useState(false),[done,setDone]=useState(null),[error,setError]=useState('');
 useEffect(()=>{setCart(readCart());const q=new URLSearchParams(window.location.search);if(q.get('checkout')==='1'){setDone(null);setOpen(true);setCheckout(true);window.history.replaceState({},'',window.location.pathname)}},[]);
 useEffect(()=>{const fn=e=>setCart(e.detail||readCart());window.addEventListener('sideii-cart',fn);return()=>window.removeEventListener('sideii-cart',fn)},[]);
 const updateCart=next=>{setCart(next);writeCart(next)};
 const [form,setForm]=useState({name:'',email:'',phone:'',address:'',city:'',district:'',postal:'',notes:''});
 const filtered=releases.filter(r=>(filter==='all'||(filter==='selected'?r.productOrigin==='distributed':r.imprint===filter))&&(formatFilter==='all'||r.variants.some(v=>v.format===formatFilter)));
 const physical=cart.some(x=>!x.digital),total=useMemo(()=>cart.reduce((s,x)=>s+x.price*x.qty,0),[cart]);
 const add=(r,v)=>{setDone(null);setCart(addCartItem(r,v));setOpen(true)};
 async function placeOrder(e){e.preventDefault();setError('');if(!supabase)return setError('Store connection unavailable.');setBusy(true);
  const address=physical?{line1:form.address,city:form.city,district:form.district,postal_code:form.postal,country:'TR'}:null;
  const items=cart.map(x=>({variant_id:x.variantId,quantity:x.qty}));
  const {data,error:rpcError}=await supabase.rpc('create_store_order',{p_email:form.email,p_full_name:form.name,p_phone:form.phone,p_address:address,p_notes:form.notes||null,p_items:items});
  setBusy(false);if(rpcError){setError(rpcError.message);return}setDone(data);updateCart([]);setCheckout(false);
 }
 return <><main className="storePage"><header className="nav shell"><Link className="brand" href="/"><img src="/brand/sideii-logo-flat.png" alt="Side II"/></Link><nav><Link href="/">Releases</Link><Link href="/#imprints">Imprints</Link><Link href="/#about">About</Link><button className="cartNav" onClick={()=>setOpen(true)}>BAG · {cart.reduce((s,x)=>s+x.qty,0)}</button></nav></header>
 <section className="storeHero shell"><span>STORE / CATALOGUE</span><h1>Available<br/><i>editions.</i></h1><p>Physical objects and digital masters from SIDE:II and its imprints.</p></section>
 <section className="storeFilters shell"><div>{[['all','ALL'],['sideii','SIDE:II'],['lethargia','LETHARGIA'],['selected','SELECTED']].map(([v,l])=><button key={v} className={filter===v?'active':''} onClick={()=>setFilter(v)}>{l}</button>)}</div><div>{[['all','ALL MEDIA'],['vinyl','VINYL'],['cd','CD'],['cassette','CASSETTE'],['digital','DIGITAL']].map(([v,l])=><button key={v} className={formatFilter===v?'active':''} onClick={()=>setFormatFilter(v)}>{l}</button>)}</div></section><section className="storeCatalogue shell">{filtered.map(r=><article className={"storeProduct "+(r.productOrigin==="distributed"?"selectedProduct":"")} key={r.slug}><Link href={'/releases/'+r.slug} className="storeCover">{r.cover?<img src={r.cover} alt={r.title}/>:<span>{r.catalogue}</span>}</Link><div className="storeProductMeta">{r.productOrigin==='distributed'&&<span className="selectedBadge">SELECTED / DISTRIBUTION</span>}<small>{r.productOrigin==='distributed'?(r.originalLabel||'SELECTED / DISTRIBUTION'):(r.imprint==='lethargia'?'LETHARGIA RECORDS':'SIDE:II')} · {r.originalCatalogue||r.catalogue}</small><h2>{r.title}</h2>{r.productOrigin==='distributed'&&<p className="selectedAttribution">Independent release by <b>{r.originalLabel||'external label'}</b>. Distributed / selected by SIDE:II.</p>}<div className="storeVariants">{r.variants.map(v=>{const unavailable=r.status!=='AVAILABLE'||(v.format!=='digital'&&v.stock<=0);return <div className="storeVariant" key={v.id||v.sku}><div><b>{v.formatLabel}</b><span>{v.format==='digital'?'DIGITAL DOWNLOAD':v.format==='vinyl'?[v.vinylSize,v.vinylSpeed,v.vinylWeight&&v.vinylWeight+'G',v.vinylColor].filter(Boolean).join(' · '):v.stock+' IN STOCK'}</span></div><strong>{fmt(v.price)}</strong><button disabled={unavailable} onClick={()=>add(r,v)}>{r.status!=='AVAILABLE'?'COMING SOON':unavailable?'SOLD OUT':'ADD'}</button></div>})}</div></div></article>)}{filtered.length===0&&<div className="storeNoResults">NO RELEASES IN THIS SELECTION.</div>}</section></main>
 <aside className={'cartDrawer '+(open?'open':'')}><button className="cartClose" onClick={()=>{setOpen(false);setCheckout(false)}}>CLOSE ×</button><span>SHOPPING BAG</span>{done?<div className="orderDone"><b>ORDER RECEIVED</b><strong>#{done.order_no}</strong><p>{fmt(done.total)}</p><small>Payment is not collected yet. Payment connection is the next step.</small></div>:checkout?<form className="checkoutForm" onSubmit={placeOrder}><h3>Checkout</h3><label>EMAIL<input type="email" required value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></label><label>FULL NAME<input required={physical} value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label>PHONE<input required={physical} value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})}/></label>{physical&&<><label>ADDRESS<textarea required value={form.address} onChange={e=>setForm({...form,address:e.target.value})}/></label><div className="checkoutSplit"><label>DISTRICT<input required value={form.district} onChange={e=>setForm({...form,district:e.target.value})}/></label><label>CITY<input required value={form.city} onChange={e=>setForm({...form,city:e.target.value})}/></label></div><label>POSTAL CODE<input value={form.postal} onChange={e=>setForm({...form,postal:e.target.value})}/></label></>}<label>ORDER NOTE<textarea value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/></label>{error&&<p className="checkoutError">{error}</p>}<div className="cartTotal"><span>TOTAL</span><strong>{fmt(total)}</strong></div><button className="checkoutButton" disabled={busy}>{busy?'CREATING ORDER…':'PLACE ORDER'}</button><button type="button" className="checkoutBack" onClick={()=>setCheckout(false)}>← BACK TO BAG</button></form>:cart.length===0?<p className="cartEmpty">Your bag is empty.</p>:<><div className="cartItems">{cart.map(x=><article key={x.key}>{x.cover&&<img src={x.cover} alt=""/>}<div><b>{x.title}</b><small>{x.format}{x.digital?' · DOWNLOAD':''}</small><div><button onClick={()=>updateCart(cart.map(y=>y.key===x.key?{...y,qty:Math.max(1,y.qty-1)}:y))}>−</button><span>{x.qty}</span><button onClick={()=>updateCart(cart.map(y=>y.key===x.key?{...y,qty:y.qty+1}:y))}>＋</button><button onClick={()=>updateCart(cart.filter(y=>y.key!==x.key))}>REMOVE</button></div></div><strong>{fmt(x.price*x.qty)}</strong></article>)}</div><div className="cartTotal"><span>SUBTOTAL</span><strong>{fmt(total)}</strong></div><button className="checkoutButton" onClick={()=>setCheckout(true)}>CHECKOUT →</button><small className="checkoutNote">{physical?'Shipping details will be requested next.':'Digital-only order · no shipping address required.'}</small></>}</aside>{open&&<button className="cartShade" aria-label="Close bag" onClick={()=>{setOpen(false);setCheckout(false)}}/>}</>
}
