'use client';
import Link from 'next/link';
import {useMemo,useState} from 'react';

const fmt=n=>new Intl.NumberFormat('tr-TR',{style:'currency',currency:'TRY',maximumFractionDigits:0}).format(Number(n||0));
export default function StoreClient({releases}){
 const [cart,setCart]=useState([]),[open,setOpen]=useState(false);
 const add=(r,v)=>{setCart(x=>{const k=v.id||v.sku,i=x.findIndex(y=>y.key===k);if(i<0)return [...x,{key:k,title:r.title,catalogue:r.catalogue,cover:r.cover,format:v.formatLabel,price:Number(v.price||0),qty:1,digital:v.format==='digital'}];return x.map((y,n)=>n===i?{...y,qty:y.qty+1}:y)});setOpen(true)};
 const total=useMemo(()=>cart.reduce((s,x)=>s+x.price*x.qty,0),[cart]);
 return <><main className="storePage"><header className="nav shell"><Link className="brand" href="/"><img src="/brand/sideii-logo-flat.png" alt="Side II"/></Link><nav><Link href="/">Releases</Link><Link href="/#imprints">Imprints</Link><Link href="/#about">About</Link><button className="cartNav" onClick={()=>setOpen(true)}>BAG · {cart.reduce((s,x)=>s+x.qty,0)}</button></nav></header>
 <section className="storeHero shell"><span>STORE / CATALOGUE</span><h1>Available<br/><i>editions.</i></h1><p>Physical objects and digital masters from SIDE:II and its imprints.</p></section>
 <section className="storeCatalogue shell">{releases.map(r=><article className="storeProduct" key={r.slug}><Link href={'/releases/'+r.slug} className="storeCover">{r.cover?<img src={r.cover} alt={r.title}/>:<span>{r.catalogue}</span>}</Link><div className="storeProductMeta"><small>{r.imprint==='lethargia'?'LETHARGIA RECORDS':'SIDE:II'} · {r.catalogue}</small><h2>{r.title}</h2><div className="storeVariants">{r.variants.map(v=>{const unavailable=r.status!=='AVAILABLE'||(v.format!=='digital'&&v.stock<=0);return <div className="storeVariant" key={v.id||v.sku}><div><b>{v.formatLabel}</b><span>{v.format==='digital'?'DIGITAL DOWNLOAD':v.stock+' IN STOCK'}</span></div><strong>{fmt(v.price)}</strong><button disabled={unavailable} onClick={()=>add(r,v)}>{r.status!=='AVAILABLE'?'COMING SOON':unavailable?'SOLD OUT':'ADD'}</button></div>})}</div></div></article>)}</section></main>
 <aside className={'cartDrawer '+(open?'open':'')}><button className="cartClose" onClick={()=>setOpen(false)}>CLOSE ×</button><span>SHOPPING BAG</span>{cart.length===0?<p className="cartEmpty">Your bag is empty.</p>:<><div className="cartItems">{cart.map(x=><article key={x.key}>{x.cover&&<img src={x.cover} alt=""/>}<div><b>{x.title}</b><small>{x.format}{x.digital?' · DOWNLOAD':''}</small><div><button onClick={()=>setCart(c=>c.map(y=>y.key===x.key?{...y,qty:Math.max(1,y.qty-1)}:y))}>−</button><span>{x.qty}</span><button onClick={()=>setCart(c=>c.map(y=>y.key===x.key?{...y,qty:y.qty+1}:y))}>＋</button><button onClick={()=>setCart(c=>c.filter(y=>y.key!==x.key))}>REMOVE</button></div></div><strong>{fmt(x.price*x.qty)}</strong></article>)}</div><div className="cartTotal"><span>SUBTOTAL</span><strong>{fmt(total)}</strong></div><button className="checkoutButton" disabled>CHECKOUT · NEXT</button><small className="checkoutNote">Checkout and payment connection is the next commerce step.</small></>}</aside>{open&&<button className="cartShade" aria-label="Close bag" onClick={()=>setOpen(false)}/>}</>
}
