'use client';
import Link from 'next/link';
import {useMemo,useState} from 'react';
import {supabase} from '../lib/supabase';

const fmt=n=>new Intl.NumberFormat('tr-TR',{style:'currency',currency:'TRY',maximumFractionDigits:0}).format(Number(n||0));
export default function StoreClient({releases}){
 const [cart,setCart]=useState([]),[open,setOpen]=useState(false),[checkout,setCheckout]=useState(false),[busy,setBusy]=useState(false),[done,setDone]=useState(null),[error,setError]=useState('');
 const [form,setForm]=useState({name:'',email:'',phone:'',address:'',city:'',district:'',postal:'',notes:''});
 const physical=cart.some(x=>!x.digital),total=useMemo(()=>cart.reduce((s,x)=>s+x.price*x.qty,0),[cart]);
 const add=(r,v)=>{setCart(x=>{const k=v.id||v.sku,i=x.findIndex(y=>y.key===k);if(i<0)return [...x,{key:k,variantId:v.id,sku:v.sku,title:r.title,catalogue:r.catalogue,cover:r.cover,format:v.formatLabel,price:Number(v.price||0),qty:1,digital:v.format==='digital'}];return x.map((y,n)=>n===i?{...y,qty:y.qty+1}:y)});setOpen(true)};
 async function placeOrder(e){e.preventDefault();setError('');if(!supabase)return setError('Store connection unavailable.');setBusy(true);
  const address=physical?{line1:form.address,city:form.city,district:form.district,postal_code:form.postal,country:'TR'}:null;
  const items=cart.map(x=>({variant_id:x.variantId,quantity:x.qty}));
  const {data,error:rpcError}=await supabase.rpc('create_store_order',{p_email:form.email,p_full_name:form.name,p_phone:form.phone,p_address:address,p_notes:form.notes||null,p_items:items});
  setBusy(false);if(rpcError){setError(rpcError.message);return}setDone(data);setCart([]);setCheckout(false);
 }
 return <><main className="storePage"><header className="nav shell"><Link className="brand" href="/"><img src="/brand/sideii-logo-flat.png" alt="Side II"/></Link><nav><Link href="/">Releases</Link><Link href="/#imprints">Imprints</Link><Link href="/#about">About</Link><button className="cartNav" onClick={()=>setOpen(true)}>BAG · {cart.reduce((s,x)=>s+x.qty,0)}</button></nav></header>
 <section className="storeHero shell"><span>STORE / CATALOGUE</span><h1>Available<br/><i>editions.</i></h1><p>Physical objects and digital masters from SIDE:II and its imprints.</p></section>
 <section className="storeCatalogue shell">{releases.map(r=><article className="storeProduct" key={r.slug}><Link href={'/releases/'+r.slug} className="storeCover">{r.cover?<img src={r.cover} alt={r.title}/>:<span>{r.catalogue}</span>}</Link><div className="storeProductMeta"><small>{r.imprint==='lethargia'?'LETHARGIA RECORDS':'SIDE:II'} · {r.catalogue}</small><h2>{r.title}</h2><div className="storeVariants">{r.variants.map(v=>{const unavailable=r.status!=='AVAILABLE'||(v.format!=='digital'&&v.stock<=0);return <div className="storeVariant" key={v.id||v.sku}><div><b>{v.formatLabel}</b><span>{v.format==='digital'?'DIGITAL DOWNLOAD':v.stock+' IN STOCK'}</span></div><strong>{fmt(v.price)}</strong><button disabled={unavailable} onClick={()=>add(r,v)}>{r.status!=='AVAILABLE'?'COMING SOON':unavailable?'SOLD OUT':'ADD'}</button></div>})}</div></div></article>)}</section></main>
 <aside className={'cartDrawer '+(open?'open':'')}><button className="cartClose" onClick={()=>{setOpen(false);setCheckout(false)}}>CLOSE ×</button><span>SHOPPING BAG</span>{done?<div className="orderDone"><b>ORDER RECEIVED</b><strong>#{done.order_no}</strong><p>{fmt(done.total)}</p><small>Payment is not collected yet. Payment connection is the next step.</small></div>:checkout?<form className="checkoutForm" onSubmit={placeOrder}><h3>Checkout</h3><label>EMAIL<input type="email" required value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></label><label>FULL NAME<input required={physical} value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label>PHONE<input required={physical} value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})}/></label>{physical&&<><label>ADDRESS<textarea required value={form.address} onChange={e=>setForm({...form,address:e.target.value})}/></label><div className="checkoutSplit"><label>DISTRICT<input required value={form.district} onChange={e=>setForm({...form,district:e.target.value})}/></label><label>CITY<input required value={form.city} onChange={e=>setForm({...form,city:e.target.value})}/></label></div><label>POSTAL CODE<input value={form.postal} onChange={e=>setForm({...form,postal:e.target.value})}/></label></>}<label>ORDER NOTE<textarea value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/></label>{error&&<p className="checkoutError">{error}</p>}<div className="cartTotal"><span>TOTAL</span><strong>{fmt(total)}</strong></div><button className="checkoutButton" disabled={busy}>{busy?'CREATING ORDER…':'PLACE ORDER'}</button><button type="button" className="checkoutBack" onClick={()=>setCheckout(false)}>← BACK TO BAG</button></form>:cart.length===0?<p className="cartEmpty">Your bag is empty.</p>:<><div className="cartItems">{cart.map(x=><article key={x.key}>{x.cover&&<img src={x.cover} alt=""/>}<div><b>{x.title}</b><small>{x.format}{x.digital?' · DOWNLOAD':''}</small><div><button onClick={()=>setCart(c=>c.map(y=>y.key===x.key?{...y,qty:Math.max(1,y.qty-1)}:y))}>−</button><span>{x.qty}</span><button onClick={()=>setCart(c=>c.map(y=>y.key===x.key?{...y,qty:y.qty+1}:y))}>＋</button><button onClick={()=>setCart(c=>c.filter(y=>y.key!==x.key))}>REMOVE</button></div></div><strong>{fmt(x.price*x.qty)}</strong></article>)}</div><div className="cartTotal"><span>SUBTOTAL</span><strong>{fmt(total)}</strong></div><button className="checkoutButton" onClick={()=>setCheckout(true)}>CHECKOUT →</button><small className="checkoutNote">{physical?'Shipping details will be requested next.':'Digital-only order · no shipping address required.'}</small></>}</aside>{open&&<button className="cartShade" aria-label="Close bag" onClick={()=>{setOpen(false);setCheckout(false)}}/>}</>
}
