'use client';

import { useEffect, useMemo, useState } from 'react';
import { supabase } from '../lib/supabase';

const STATUS=[['draft','DRAFT'],['forthcoming','FORTHCOMING'],['active','AVAILABLE'],['archived','ARCHIVED']];
const FORMATS=['cd','cassette','digital'];

const cleanVariant=(v={})=>({id:v.id||null,sku:v.sku||'',format:v.format||'cd',price:String(v.price??0),stock:String(v.stock_qty??0),reserved_qty:Number(v.reserved_qty||0),manufactured_qty:Number(v.manufactured_qty||0),edition_name:v.edition_name||'',edition_details:v.edition_details||'',digital_formats:Array.isArray(v.digital_formats)?v.digital_formats.join(', '):'WAV, FLAC, MP3',audio_specs:v.audio_specs||'24 BIT / 44.1 kHz',active:v.active!==false});

export default function EditReleaseModal({product,onClose,onSaved}){
 const initialVariants=(product?.product_variants||[]).map(cleanVariant);
 const [tab,setTab]=useState('release');
 const [form,setForm]=useState({catalogue_no:product.catalogue_no||'',title:product.title||'',artist_project:product.artist_project||'',description:product.description||'',imprint:product.imprint||'sideii',status:product.status||'draft',has_shrinkwrap:!!product.has_shrinkwrap,release_date:product.release_date||'',credits:product.credits||'',tracklist:Array.isArray(product.tracklist)?product.tracklist.join('\n'):''});
 const [variants,setVariants]=useState(initialVariants.length?initialVariants:[cleanVariant({sku:`${product.catalogue_no||'SIDEII'}-CD`})]);
 const [removedVariants,setRemovedVariants]=useState([]);
 const [file,setFile]=useState(null); const [preview,setPreview]=useState(''); const [gallery,setGallery]=useState(Array.isArray(product.gallery_paths)?product.gallery_paths:[]); const [galleryFiles,setGalleryFiles]=useState([]);
 const [saving,setSaving]=useState(false); const [message,setMessage]=useState('');
 const set=(k,v)=>setForm(p=>({...p,[k]:v}));
 useEffect(()=>()=>{if(preview)URL.revokeObjectURL(preview);galleryFiles.forEach(x=>URL.revokeObjectURL(x.preview))},[preview,galleryFiles]);
 const publicUrl=path=>supabase.storage.from('release-artwork').getPublicUrl(path).data.publicUrl;
 const current=product.artwork_path?publicUrl(product.artwork_path):'';
 const existingGallery=useMemo(()=>gallery.map((path,i)=>({kind:'existing',path,preview:publicUrl(path),name:`Gallery ${i+1}`})),[gallery]);

 function validImage(f){return f&&f.type.startsWith('image/')&&f.size<=10*1024*1024}
 function pick(f){if(preview)URL.revokeObjectURL(preview);if(!f){setFile(null);setPreview('');return}if(!validImage(f)){setMessage('Use JPG, PNG, WEBP or AVIF up to 10 MB.');return}setFile(f);setPreview(URL.createObjectURL(f));setMessage('')}
 function addGallery(files){const next=[...files].filter(validImage).map(f=>({file:f,preview:URL.createObjectURL(f),name:f.name}));if(next.length!==files.length)setMessage('Some files were skipped. Images must be 10 MB or smaller.');setGalleryFiles(p=>[...p,...next])}
 function removeExisting(path){setGallery(p=>p.filter(x=>x!==path))}
 function removeNew(i){setGalleryFiles(p=>{URL.revokeObjectURL(p[i].preview);return p.filter((_,n)=>n!==i)})}
 function moveExisting(i,dir){setGallery(p=>{const n=[...p],j=i+dir;if(j<0||j>=n.length)return p;[n[i],n[j]]=[n[j],n[i]];return n})}
 function updateVariant(i,k,v){setVariants(p=>p.map((x,n)=>n===i?{...x,[k]:v}:x))}
 function addVariant(){const format=!variants.some(v=>v.format==='cd')?'cd':!variants.some(v=>v.format==='cassette')?'cassette':'digital';setVariants(p=>[...p,cleanVariant({sku:`${form.catalogue_no||'SIDEII'}-${format==='cd'?'CD':format==='cassette'?'CS':'DIG'}-${p.length+1}`,format,edition_name:form.title})])}
 function removeVariant(i){const v=variants[i];if(v.id)setRemovedVariants(p=>[...p,v.id]);setVariants(p=>p.filter((_,n)=>n!==i))}

 async function save(){
  if(!variants.length){setMessage('Keep at least one edition.');setTab('media');return}
  setSaving(true);setMessage('');
  try{
   let artworkPath=product.artwork_path||null;
   if(file){const ext=(file.name.split('.').pop()||'jpg').toLowerCase().replace(/[^a-z0-9]/g,'');const path=`${product.id}/cover.${ext}`;const {error:u}=await supabase.storage.from('release-artwork').upload(path,file,{upsert:true,contentType:file.type,cacheControl:'3600'});if(u)throw u;if(artworkPath&&artworkPath!==path)await supabase.storage.from('release-artwork').remove([artworkPath]);artworkPath=path}
   const uploaded=[];
   for(const item of galleryFiles){const ext=(item.file.name.split('.').pop()||'jpg').toLowerCase().replace(/[^a-z0-9]/g,'');const path=`${product.id}/gallery/${Date.now()}-${uploaded.length}.${ext}`;const {error}=await supabase.storage.from('release-artwork').upload(path,item.file,{upsert:false,contentType:item.file.type,cacheControl:'3600'});if(error)throw error;uploaded.push(path)}
   const removed=(Array.isArray(product.gallery_paths)?product.gallery_paths:[]).filter(x=>!gallery.includes(x));if(removed.length)await supabase.storage.from('release-artwork').remove(removed);
   const galleryPaths=[...gallery,...uploaded];
   const isPublic=['active','forthcoming'].includes(form.status);
   const {error:p}=await supabase.from('products').update({catalogue_no:form.catalogue_no.trim(),title:form.title.trim(),artist_project:form.artist_project.trim()||null,description:form.description.trim()||null,imprint:form.imprint,status:form.status,is_public:isPublic,has_shrinkwrap:form.has_shrinkwrap,release_date:form.release_date||null,credits:form.credits.trim()||null,tracklist:form.tracklist.split('\n').map(x=>x.trim()).filter(Boolean),artwork_path:artworkPath,gallery_paths:galleryPaths}).eq('id',product.id);if(p)throw p;
   for(const id of removedVariants){const {error}=await supabase.from('product_variants').delete().eq('id',id);if(error)throw error}
   for(const [i,v] of variants.entries()){const stock=Math.max(0,parseInt(v.stock||'0',10)||0),price=Math.max(0,parseFloat(v.price||'0')||0);const payload={product_id:product.id,sku:v.sku.trim()||`${form.catalogue_no}-${v.format.toUpperCase()}-${i+1}`,format:v.format,price,currency:'TRY',stock_qty:stock,manufactured_qty:Math.max(stock+Number(v.reserved_qty||0),Number(v.manufactured_qty||0)),reserved_qty:Number(v.reserved_qty||0),edition_name:v.edition_name.trim()||form.title.trim(),edition_details:v.edition_details.trim()||null,digital_formats:v.format==='digital'?v.digital_formats.split(',').map(x=>x.trim().toUpperCase()).filter(Boolean):[],audio_specs:v.format==='digital'?(v.audio_specs.trim()||null):null,active:v.active};const q=v.id?supabase.from('product_variants').update(payload).eq('id',v.id):supabase.from('product_variants').insert(payload);const {error}=await q;if(error)throw error}
   await onSaved();onClose();
  }catch(e){setMessage(e?.message||'Update failed.')}finally{setSaving(false)}
 }

 return <div className="editOverlay" onMouseDown={e=>{if(e.target===e.currentTarget)onClose()}}><section className="editModal releaseV2Modal"><header><div><span>EDIT / RELEASE V2</span><h2>{product.title}</h2></div><button onClick={onClose}>CLOSE ×</button></header>
 <nav className="editTabs">{[['release','RELEASE'],['media',`MEDIA · ${variants.length}`],['gallery',`GALLERY · ${gallery.length+galleryFiles.length}`]].map(([v,l])=><button key={v} className={tab===v?'active':''} onClick={()=>setTab(v)}>{l}</button>)}</nav>
 {tab==='release'&&<div className="editBody"><div className="editFields">
 <label>IMPRINT<select value={form.imprint} onChange={e=>set('imprint',e.target.value)}><option value="sideii">SIDE:II</option><option value="lethargia">LETHARGIA RECORDS</option></select></label><label>CATALOGUE NO.<input value={form.catalogue_no} onChange={e=>set('catalogue_no',e.target.value)}/></label><label>TITLE<input value={form.title} onChange={e=>set('title',e.target.value)}/></label><label>STATUS<select value={form.status} onChange={e=>set('status',e.target.value)}>{STATUS.map(([v,l])=><option value={v} key={v}>{l}</option>)}</select></label><label>RELEASE DATE<input type="date" value={form.release_date} onChange={e=>set('release_date',e.target.value)}/></label><label>ARTIST / PROJECT<input value={form.artist_project} onChange={e=>set('artist_project',e.target.value)}/></label>
 <label className="editWide">TRACKLIST · ONE TRACK PER LINE<textarea rows="6" value={form.tracklist} onChange={e=>set('tracklist',e.target.value)}/></label><label className="editWide">CREDITS<textarea rows="5" value={form.credits} onChange={e=>set('credits',e.target.value)}/></label><label className="editWide">DESCRIPTION<textarea rows="4" value={form.description} onChange={e=>set('description',e.target.value)}/></label><label className="editWide">PRIMARY ARTWORK<input type="file" accept="image/jpeg,image/png,image/webp,image/avif" onChange={e=>pick(e.target.files?.[0]||null)}/></label><label className="editWide editCheck"><input type="checkbox" checked={form.has_shrinkwrap} onChange={e=>set('has_shrinkwrap',e.target.checked)}/><span>SHRINKWRAP / CELLOPHANE</span></label>
 </div><aside className="editArtwork">{(preview||current)?<img src={preview||current} alt=""/>:<div>NO ARTWORK</div>}<small>{file?'NEW ARTWORK':'CURRENT ARTWORK'}</small></aside></div>}
 {tab==='media'&&<div className="editionManager"><div className="editionManagerHead"><div><span>EDITIONS / MEDIA</span><p>CD, cassette and digital editions with independent SKU, price and availability.</p></div><button onClick={addVariant}>＋ ADD EDITION</button></div>{variants.map((v,i)=><article className="editionEditor" key={v.id||`new-${i}`}><header><strong>{String(i+1).padStart(2,'0')} / {v.format.toUpperCase()}</strong><button onClick={()=>removeVariant(i)} disabled={variants.length===1}>REMOVE</button></header><div><label>FORMAT<select value={v.format} onChange={e=>updateVariant(i,'format',e.target.value)}>{FORMATS.map(x=><option key={x} value={x}>{x.toUpperCase()}</option>)}</select></label><label>SKU<input value={v.sku} onChange={e=>updateVariant(i,'sku',e.target.value)}/></label><label>PRICE / TRY<input type="number" min="0" step=".01" value={v.price} onChange={e=>updateVariant(i,'price',e.target.value)}/></label>{v.format==='digital'?<label>AVAILABILITY<input value="UNLIMITED" disabled/></label>:<label>STOCK<input type="number" min="0" value={v.stock} onChange={e=>updateVariant(i,'stock',e.target.value)}/></label>}{v.format==='digital'&&<><label className="editionWide">DOWNLOAD FORMATS<input value={v.digital_formats} onChange={e=>updateVariant(i,'digital_formats',e.target.value)} placeholder="WAV, FLAC, MP3"/></label><label className="editionWide">AUDIO MASTER<input value={v.audio_specs} onChange={e=>updateVariant(i,'audio_specs',e.target.value)} placeholder="24 BIT / 44.1 kHz"/></label></>}<label className="editionWide">EDITION / PRESSING<input value={v.edition_details} onChange={e=>updateVariant(i,'edition_details',e.target.value)} placeholder="First pressing · 100 copies"/></label><label className="editionActive"><input type="checkbox" checked={v.active} onChange={e=>updateVariant(i,'active',e.target.checked)}/> ACTIVE EDITION</label></div></article>)}</div>}
 {tab==='gallery'&&<div className="galleryManager"><div className="galleryManagerHead"><div><span>OBJECT / GALLERY</span><p>Back cover, booklet, disc face and product photography. Order is preserved.</p></div><label>＋ ADD IMAGES<input type="file" multiple accept="image/jpeg,image/png,image/webp,image/avif" onChange={e=>{addGallery(e.target.files||[]);e.target.value=''}}/></label></div><div className="galleryAdminGrid">{existingGallery.map((g,i)=><article key={g.path}><img src={g.preview} alt=""/><div><span>{String(i+1).padStart(2,'0')}</span><button disabled={i===0} onClick={()=>moveExisting(i,-1)}>↑</button><button disabled={i===gallery.length-1} onClick={()=>moveExisting(i,1)}>↓</button><button onClick={()=>removeExisting(g.path)}>REMOVE</button></div></article>)}{galleryFiles.map((g,i)=><article key={g.preview} className="galleryNew"><img src={g.preview} alt=""/><div><span>NEW</span><button onClick={()=>removeNew(i)}>REMOVE</button></div></article>)}{gallery.length+galleryFiles.length===0&&<div className="galleryEmpty">NO GALLERY IMAGES YET<br/><small>Primary artwork remains the catalogue cover.</small></div>}</div></div>}
 {message&&<p className="workspaceMessage">{message}</p>}<footer><button className="ghostButton" onClick={onClose}>CANCEL</button><button className="saveButton" disabled={saving} onClick={save}>{saving?'SAVING…':'SAVE RELEASE V2 →'}</button></footer></section></div>
}
