'use client';
import {useState} from 'react';
import {supabase} from '../lib/supabase';

export default function MerchEditor({product,onClose,onSaved,embedded=false}){
 const [meta,setMeta]=useState({title:product.title||'',description:product.description||'',status:product.status||'draft',cover_url:product.cover_url||''});
 const base=product.product_variants?.[0]||{};
 const [v,setV]=useState({size:'',color:base.option_color||'BLACK',style:base.option_style||'',price:base.price||'',stock:'',weight_g:base.weight_g||'',sku:''});
 const [msg,setMsg]=useState(''),[busy,setBusy]=useState(false);
 async function upload(file){if(!file)return;setBusy(true);setMsg('Uploading image…');const ext=file.name.split('.').pop()?.toLowerCase()||'jpg';const path=`merch/${product.id}/${Date.now()}.${ext}`;const {error}=await supabase.storage.from('release-artwork').upload(path,file,{upsert:false});if(error){setBusy(false);setMsg(error.message);return}const {data}=supabase.storage.from('release-artwork').getPublicUrl(path);setMeta(x=>({...x,cover_url:data.publicUrl}));setBusy(false);setMsg('Image ready — save product to apply.')}
 async function saveMeta(){setBusy(true);setMsg('');const {error}=await supabase.rpc('admin_update_merch_product',{p_product_id:product.id,p_title:meta.title,p_description:meta.description||null,p_status:meta.status,p_cover_url:meta.cover_url||null});setBusy(false);if(error){setMsg(error.message);return}setMsg('Product saved.');if(onSaved)await onSaved();}
 async function addVariant(){if(product.merch_category==='apparel'&&!v.size){setMsg('Select a size.');return}setBusy(true);setMsg('');const {error}=await supabase.rpc('admin_add_merch_variant',{p_product_id:product.id,p_size:v.size||null,p_color:v.color||null,p_style:v.style||null,p_price:Number(v.price)||0,p_stock:parseInt(v.stock||'0',10)||0,p_weight_g:v.weight_g?parseInt(v.weight_g,10):null,p_sku:v.sku||null});setBusy(false);if(error){setMsg(error.message);return}setMsg('Variant added.');setV(x=>({...x,size:'',stock:'',sku:''}));}
 return <div className={embedded?'merchEmbedded':'modalBackdrop'}><section className="orderModal merchEditor"><header><div><span>MERCH / {product.catalogue_no}</span><h2>{product.title}</h2></div><button onClick={onClose}>CLOSE ×</button></header>
 <div className="merchEditorGrid"><div className="merchImagePanel">{meta.cover_url?<img src={meta.cover_url} alt=""/>:<div className="merchImageEmpty">NO PRODUCT IMAGE</div>}<label className="uploadButton">UPLOAD IMAGE<input type="file" accept="image/jpeg,image/png,image/webp" hidden onChange={e=>upload(e.target.files?.[0])}/></label></div>
 <div className="formGrid compact"><label><span>PRODUCT NAME</span><input value={meta.title} onChange={e=>setMeta({...meta,title:e.target.value})}/></label><label><span>STATUS</span><select value={meta.status} onChange={e=>setMeta({...meta,status:e.target.value})}><option value="draft">DRAFT</option><option value="forthcoming">FORTHCOMING</option><option value="active">AVAILABLE</option><option value="archived">ARCHIVED</option></select></label><label className="wideField"><span>DESCRIPTION</span><textarea rows="4" value={meta.description} onChange={e=>setMeta({...meta,description:e.target.value})}/></label><button className="saveButton" disabled={busy} onClick={saveMeta}>SAVE PRODUCT</button></div></div>
 <div className="variantList"><span>EXISTING VARIANTS</span>{product.product_variants?.map(x=><article key={x.id}><b>{x.option_size||'ONE SIZE'} · {x.option_color||'DEFAULT'}</b><small>{x.sku} · ₺{Number(x.price).toFixed(2)} · {x.stock_qty} IN STOCK</small></article>)}</div>
 <div className="variantBuilder"><span>ADD VARIANT</span><div className="formGrid compact">{product.merch_category==='apparel'&&<label><span>SIZE</span><select value={v.size} onChange={e=>setV({...v,size:e.target.value})}><option value="">SELECT SIZE</option><option>S</option><option>M</option><option>L</option><option>XL</option><option>XXL</option></select></label>}<label><span>COLOR</span><input value={v.color} onChange={e=>setV({...v,color:e.target.value})}/></label><label><span>PRICE / TRY</span><input type="number" step=".01" value={v.price} onChange={e=>setV({...v,price:e.target.value})}/></label><label><span>STOCK</span><input type="number" min="0" value={v.stock} onChange={e=>setV({...v,stock:e.target.value})}/></label><label><span>STYLE</span><input value={v.style} onChange={e=>setV({...v,style:e.target.value})}/></label><label><span>WEIGHT / G</span><input type="number" min="0" value={v.weight_g} onChange={e=>setV({...v,weight_g:e.target.value})}/></label><label className="wideField"><span>SKU · OPTIONAL</span><input value={v.sku} onChange={e=>setV({...v,sku:e.target.value})}/></label></div><button className="saveButton" disabled={busy} onClick={addVariant}>＋ ADD VARIANT</button></div>{msg&&<p className="workspaceMessage">{msg}</p>}</section></div>
}
