'use client';
import {useEffect,useMemo,useState} from 'react';
import {usePathname} from 'next/navigation';
import {supabase} from '../lib/supabase';
import {readCart,writeCart} from '../lib/cart';
import TurkeyAddressFields from './TurkeyAddressFields';
const fmt=n=>new Intl.NumberFormat('tr-TR',{style:'currency',currency:'TRY',maximumFractionDigits:0}).format(Number(n||0));
export default function GlobalBag(){
 const pathname=usePathname(),[cart,setCart]=useState([]),[open,setOpen]=useState(false),[checkout,setCheckout]=useState(false),[busy,setBusy]=useState(false),[done,setDone]=useState(null),[error,setError]=useState('');
 const[form,setForm]=useState({name:'',email:'',phone:'',address:'',city:'',district:'',postal:'',notes:''});
 useEffect(()=>{const sync=e=>setCart(e?.detail||readCart());const openBag=()=>setOpen(true);sync();window.addEventListener('sideii-cart',sync);window.addEventListener('sideii-open-bag',openBag);return()=>{window.removeEventListener('sideii-cart',sync);window.removeEventListener('sideii-open-bag',openBag)}},[]);
 const total=useMemo(()=>cart.reduce((s,x)=>s+x.price*x.qty,0),[cart]),physical=cart.some(x=>!x.digital),update=n=>{setCart(n);writeCart(n)};
 async function placeOrder(e){e.preventDefault();setError('');if(!supabase)return setError('Store connection unavailable.');setBusy(true);const address=physical?{line1:form.address,city:form.city,district:form.district,postal_code:form.postal,country:'TR'}:null;const items=cart.map(x=>({variant_id:x.variantId,quantity:x.qty}));const {data,error:rpcError}=await supabase.rpc('create_store_order',{p_email:form.email,p_full_name:form.name,p_phone:form.phone,p_address:address,p_notes:form.notes||null,p_items:items});setBusy(false);if(rpcError)return setError(rpcError.message);setDone(data);update([]);setCheckout(false)}
 if(pathname==='/store')return null;
 const close=()=>{setOpen(false);setCheckout(false);setError('')};
 return <><button className="globalBagTrigger" onClick={()=>{setDone(null);setOpen(true)}}>BAG · {cart.reduce((s,x)=>s+x.qty,0)}</button><aside className={'globalBagDrawer '+(open?'open':'')}><button className="globalBagClose" onClick={close}>CLOSE ×</button><span>SHOPPING BAG</span>
 {done?<div className="orderDone"><b>ORDER RECEIVED</b><strong>#{done.order_no}</strong><p>{fmt(done.total)}</p><small>Payment is not collected yet.</small></div>
 :checkout?<form className="checkoutForm globalCheckout" onSubmit={placeOrder}><h3>Checkout</h3><label>EMAIL<input type="email" required value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></label><label>FULL NAME<input required={physical} value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label>PHONE<input required={physical} value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})}/></label>{physical&&<><label>ADDRESS<textarea required value={form.address} onChange={e=>setForm({...form,address:e.target.value})}/></label><TurkeyAddressFields form={form} setForm={setForm}/><label>POSTAL CODE<input value={form.postal} onChange={e=>setForm({...form,postal:e.target.value})}/></label></>}<label>ORDER NOTE<textarea value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/></label>{error&&<p className="checkoutError">{error}</p>}<div className="globalBagTotal"><span>TOTAL</span><strong>{fmt(total)}</strong></div><button className="globalBagCheckout" disabled={busy}>{busy?'CREATING ORDER…':'PLACE ORDER'}</button><button type="button" className="checkoutBack" onClick={()=>setCheckout(false)}>← BACK TO BAG</button></form>
 :cart.length===0?<p className="globalBagEmpty">Your bag is empty.</p>:<><div className="globalBagItems">{cart.map(x=><article key={x.key}>{x.cover&&<img src={x.cover} alt=""/>}<div><b>{x.title}</b><small>{x.format}{x.digital?' · DOWNLOAD':''}</small><div className="globalBagQty"><button onClick={()=>update(cart.map(y=>y.key===x.key?{...y,qty:Math.max(1,y.qty-1)}:y))}>−</button><span>{x.qty}</span><button onClick={()=>update(cart.map(y=>y.key===x.key?{...y,qty:y.qty+1}:y))}>＋</button><button onClick={()=>update(cart.filter(y=>y.key!==x.key))}>REMOVE</button></div></div><strong>{fmt(x.price*x.qty)}</strong></article>)}</div><div className="globalBagTotal"><span>SUBTOTAL</span><strong>{fmt(total)}</strong></div><button className="globalBagCheckout" onClick={()=>setCheckout(true)}>CHECKOUT →</button><small className="checkoutNote">{physical?'Shipping details will be requested next.':'Digital-only order · no shipping address required.'}</small></>}</aside>{open&&<button className="globalBagShade" aria-label="Close bag" onClick={close}/>}</>
}