'use client';
import {useEffect,useRef,useState} from 'react';
import {addCartItem,readCart} from '../../lib/cart';
import {supabase} from '../../lib/supabase';
import {useLocaleCurrency} from '../../components/LocaleCurrencyProvider';
import EditionVisual from '../../components/EditionVisual';

export default function EditionSelector({release}){
 const {money}=useLocaleCurrency();
 const variants=release.variants||[];const detail=release.storefrontConfig?.detail||{};const defaultVariant=detail.default_variant;const defaultIndex=Math.max(0,variants.findIndex(x=>String(x.id||x.sku)===String(defaultVariant)));const[index,setIndex]=useState(defaultVariant&&defaultVariant!=='auto'?defaultIndex:0);const[added,setAdded]=useState(false);const[bagCount,setBagCount]=useState(0);const[waitEmail,setWaitEmail]=useState(''),[waitMessage,setWaitMessage]=useState(''),[waitBusy,setWaitBusy]=useState(false);const[preorderProgress,setPreorderProgress]=useState(null);const[showBack,setShowBack]=useState(false);const[flipPhase,setFlipPhase]=useState('idle');const flipTimers=useRef([]); useEffect(()=>{const sync=()=>setBagCount(readCart().reduce((s,x)=>s+x.qty,0));sync();window.addEventListener('sideii-cart',sync);return()=>window.removeEventListener('sideii-cart',sync)},[]);const v=variants[index]||{};const media=v.media||release.media,isCassette=media==='cassette',isDigital=media==='digital',isVinyl=media==='vinyl';const soldOut=!isDigital&&Number(v.stock||0)<=0,canPreorder=soldOut&&v.preorderEnabled;const label=isDigital?'Digital edition':isCassette?'Cassette edition':isVinyl?'Vinyl edition':'CD edition';
 useEffect(()=>{const token=new URLSearchParams(window.location.search).get('variant');if(!token)return;const i=variants.findIndex(x=>String(x.sku||x.id)===token||String(x.id||'')===token);if(i>=0)setIndex(i)},[]);
 const clearFlipTimers=()=>{flipTimers.current.forEach(clearTimeout);flipTimers.current=[]};
 useEffect(()=>()=>{flipTimers.current.forEach(clearTimeout)},[]);
 const flipEdition=()=>{
  if(isDigital||flipPhase!=='idle')return;
  clearFlipTimers();setFlipPhase('retract');
  flipTimers.current.push(setTimeout(()=>{setShowBack(p=>!p);setFlipPhase('turning')},320));
  flipTimers.current.push(setTimeout(()=>setFlipPhase('idle'),1310));
 };
 const selectVariant=i=>{clearFlipTimers();setFlipPhase('idle');setIndex(i);setShowBack(false);const token=variants[i]?.sku||variants[i]?.id;if(!token)return;const url=new URL(window.location.href);url.searchParams.set('variant',token);history.replaceState(null,'',url.pathname+url.search+url.hash)};
 useEffect(()=>{let live=true;setPreorderProgress(null);if(!v?.id||!v?.preorderTarget)return()=>{live=false};supabase?.rpc('get_preorder_progress',{p_variant_id:v.id}).then(({data})=>{if(!live)return;const row=Array.isArray(data)?data[0]:data;setPreorderProgress(row||null)});return()=>{live=false}},[v?.id,v?.preorderTarget]);
 const add=()=>{const next=addCartItem(release,v);setBagCount(next.reduce((s,x)=>s+x.qty,0));setAdded(true);setTimeout(()=>setAdded(false),1400)};
 async function joinWaitlist(){const email=waitEmail.trim();if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)){setWaitMessage('Enter a valid email.');return}setWaitBusy(true);setWaitMessage('');const {error}=await supabase.rpc('join_stock_waitlist',{p_variant_id:v.id,p_email:email});setWaitBusy(false);setWaitMessage(error?error.message:'You are on the restock list.');}
 return <div className="editionExperience">{isDigital?<div key={"digital-"+(v.id||v.sku||index)} className="editionDigitalStage"><EditionVisual release={release} variant={v}/></div>:<div className={"editionFlipStage isInteractive phase-"+flipPhase} role="button" tabIndex={0} aria-pressed={showBack} aria-label={showBack?"Turn physical edition to front":"Turn physical edition to back and view tracklist"} onClick={flipEdition} onKeyDown={e=>{if(e.key==="Enter"||e.key===" "){e.preventDefault();flipEdition()}}}>
  <div className={'editionFlipObject'+(showBack?' isFlipped':'')}>
   <div className="editionFlipFace editionFlipFront"><EditionVisual release={release} variant={v}/></div>
   <div className="editionFlipFace editionFlipBack"><EditionVisual release={release} variant={v} backFace className="physicalBackVisual"/></div>
  </div>
  
 </div>}<div className="editionPanel"><p className="editionDynamicLead">{label}<small>{release.imprint==='lethargia'?'LETHARGIA':'SIDE:II'} catalogue.</small></p>{variants.length>1&&<div className="editionChooser"><span>CHOOSE EDITION</span><div>{variants.map((x,i)=><button type="button" aria-pressed={i===index} className={i===index?'active':''} onClick={()=>selectVariant(i)} key={x.id||x.sku}>{x.formatLabel}</button>)}</div></div>}<dl className="editionFacts"><div><dt>FORMAT</dt><dd>{v.formatDetail||release.formatDetail}</dd></div><div><dt>EDITION</dt><dd>{v.edition||release.edition}</dd></div>{isVinyl&&<><div><dt>VINYL</dt><dd>{[v.vinylSize,v.vinylSpeed,v.vinylWeight&&v.vinylWeight+' G'].filter(Boolean).join(' · ')||'VINYL'}</dd></div><div><dt>COLOR</dt><dd>{v.vinylColor||'BLACK'}</dd></div></>}{isDigital&&<><div><dt>FILES</dt><dd>{v.digitalFormats?.join(' · ')||'WAV · FLAC · MP3'}</dd></div><div><dt>MASTER</dt><dd>{v.audioSpecs||'DIGITAL MASTER'}</dd></div></>}<div><dt>AVAILABILITY</dt><dd>{isDigital?'UNLIMITED':soldOut?(canPreorder?'PRE-ORDER':'SOLD OUT'):(v.stock??release.stock)+' IN STOCK'}{v.editionNumberingEnabled&&v.editionTotal?' · LIMITED '+v.editionTotal:''}</dd></div></dl>{preorderProgress&&Number(preorderProgress.target)>0&&<div className="preorderMilestone"><div><span>PRODUCTION MILESTONE</span><b>{preorderProgress.paid_units} / {preorderProgress.target}</b></div><i><em style={{width:Math.min(100,(Number(preorderProgress.paid_units||0)/Number(preorderProgress.target))*100)+'%'}}/></i><small>{preorderProgress.reached?'TARGET REACHED':preorderProgress.remaining+' MORE PRE-ORDERS TO TARGET'}{preorderProgress.deadline?' · '+new Date(preorderProgress.deadline).toLocaleDateString('en-GB'):''}</small></div>}{release.status==='ARCHIVED'?<button className="productButton" disabled>ARCHIVED · NOT FOR SALE</button>:release.status==='FORTHCOMING'?<button className="productButton" disabled>COMING SOON</button>:soldOut&&!canPreorder?<><button className="productButton" disabled>SOLD OUT</button><div className="releaseWaitlist"><input type="email" placeholder="EMAIL FOR RESTOCK ALERT" value={waitEmail} onChange={e=>setWaitEmail(e.target.value)}/><button type="button" disabled={waitBusy} onClick={joinWaitlist}>{waitBusy?'SAVING…':'NOTIFY ME'}</button>{waitMessage&&<small>{waitMessage}</small>}</div></>:<button type="button" className="productButton" onClick={add}>{added?'ADDED TO BAG ✓':canPreorder?'PRE-ORDER · '+(v.price!=null?money(v.price):''):'ADD TO CART · '+(v.price!=null?money(v.price):'')}</button>}<a className="releaseBagLink" href="/store?checkout=1">BAG · {bagCount}</a></div></div>
}
