'use client';
import {useEffect,useState} from 'react';
import {addCartItem,readCart} from '../../lib/cart';
import {supabase} from '../../lib/supabase';

function VinylObject({variant,release}){const color=String(variant.vinylColor||'BLACK').toLowerCase();return <div className="productVinylObject" aria-hidden="true"><div className={'productVinylDisc vinyl-'+color.replace(/[^a-z0-9]+/g,'-')}><div className="vinylGrooves"/><div className="vinylLabel">{release.cover&&<img src={release.cover} alt=""/>}<span className="vinylLabelShade"/><i/></div></div></div>}
function DigitalCard({variant}){const bars=[22,38,58,31,74,46,86,52,68,35,79,43,61,27,49,72,40,57,30,64,45,78,36,55];return <div className="digitalMaster" aria-hidden="true"><div className="digitalMasterTop"><span>DIGITAL MASTER</span><b>∞</b></div><div className="digitalWave">{bars.map((h,i)=><i key={i} style={{'--wave':h+'%'}}/>)}</div><div className="digitalMasterFoot"><span>{variant.digitalFormats?.join(' · ')||'WAV · FLAC · MP3'}</span><small>{variant.audioSpecs||'LOSSLESS / HIGH RES'}</small></div></div>}
export default function EditionSelector({release}){
 const variants=release.variants||[];const[index,setIndex]=useState(0);const[added,setAdded]=useState(false);const[bagCount,setBagCount]=useState(0);const[waitEmail,setWaitEmail]=useState(''),[waitMessage,setWaitMessage]=useState(''),[waitBusy,setWaitBusy]=useState(false); useEffect(()=>{const sync=()=>setBagCount(readCart().reduce((s,x)=>s+x.qty,0));sync();window.addEventListener('sideii-cart',sync);return()=>window.removeEventListener('sideii-cart',sync)},[]);const v=variants[index]||{};const media=v.media||release.media,isCassette=media==='cassette',isDigital=media==='digital',isVinyl=media==='vinyl';const soldOut=!isDigital&&Number(v.stock||0)<=0,canPreorder=soldOut&&v.preorderEnabled;const label=isDigital?'Digital edition':isCassette?'Cassette edition':isVinyl?'Vinyl edition':'CD edition';
 const add=()=>{const next=addCartItem(release,v);setBagCount(next.reduce((s,x)=>s+x.qty,0));setAdded(true);setTimeout(()=>setAdded(false),1400)};
 async function joinWaitlist(){const email=waitEmail.trim();if(!/^[^\\s@]+@[^\\s@]+\\.[^\\s@]+$/.test(email)){setWaitMessage('Enter a valid email.');return}setWaitBusy(true);setWaitMessage('');const {error}=await supabase.rpc('join_stock_waitlist',{p_variant_id:v.id,p_email:email});setWaitBusy(false);setWaitMessage(error?error.message:'You are on the restock list.');}
 return <div className="editionExperience"><div className={'productVisual '+media}>{isDigital?<DigitalCard variant={v}/>:isCassette?<div className="productCassette" aria-hidden="true"><div className="productCassetteLabel"><span>{release.imprint==='lethargia'?'LETHARGIA':'SIDE:II'}</span><b>{release.number}</b></div><div className="productCassetteWindow"><i/><i/></div><div className="productCassetteBase"><i/><i/><i/></div></div>:isVinyl?<VinylObject variant={v} release={release}/>:<div className="productCdObject" aria-hidden="true"><div className="productCdDisc"><i/><b>{release.imprint==='lethargia'?'LETH':'SIDE:II'}</b><span>{release.number}</span></div></div>}<div className={'productCover'+(release.hasShrinkwrap&&!isDigital?' shrinkwrap':'')}>{release.cover?<img className="productArtwork" src={release.cover} alt={release.artist+' — '+release.title}/>:<><span>{release.catalogue}</span><b>{release.number}</b><em>{release.title}</em></>}</div></div><div className="editionPanel"><p className="editionDynamicLead">{label}<small>{release.imprint==='lethargia'?'LETHARGIA':'SIDE:II'} catalogue.</small></p>{variants.length>1&&<div className="editionChooser"><span>CHOOSE EDITION</span><div>{variants.map((x,i)=><button type="button" className={i===index?'active':''} onClick={()=>setIndex(i)} key={x.id||x.sku}>{x.formatLabel}</button>)}</div></div>}<dl className="editionFacts"><div><dt>FORMAT</dt><dd>{v.formatDetail||release.formatDetail}</dd></div><div><dt>EDITION</dt><dd>{v.edition||release.edition}</dd></div>{isVinyl&&<><div><dt>VINYL</dt><dd>{[v.vinylSize,v.vinylSpeed,v.vinylWeight&&v.vinylWeight+' G'].filter(Boolean).join(' · ')||'VINYL'}</dd></div><div><dt>COLOR</dt><dd>{v.vinylColor||'BLACK'}</dd></div></>}{isDigital&&<><div><dt>FILES</dt><dd>{v.digitalFormats?.join(' · ')||'WAV · FLAC · MP3'}</dd></div><div><dt>MASTER</dt><dd>{v.audioSpecs||'DIGITAL MASTER'}</dd></div></>}<div><dt>AVAILABILITY</dt><dd>{isDigital?'UNLIMITED':soldOut?(canPreorder?'PRE-ORDER':'SOLD OUT'):(v.stock??release.stock)+' IN STOCK'}{v.editionNumberingEnabled&&v.editionTotal?' · LIMITED '+v.editionTotal:''}</dd></div></dl>{release.status==='FORTHCOMING'?<button className="productButton" disabled>COMING SOON</button>:soldOut&&!canPreorder?<><button className="productButton" disabled>SOLD OUT</button><div className="releaseWaitlist"><input type="email" placeholder="EMAIL FOR RESTOCK ALERT" value={waitEmail} onChange={e=>setWaitEmail(e.target.value)}/><button type="button" disabled={waitBusy} onClick={joinWaitlist}>{waitBusy?'SAVING…':'NOTIFY ME'}</button>{waitMessage&&<small>{waitMessage}</small>}</div></>:<button type="button" className="productButton" onClick={add}>{added?'ADDED TO BAG ✓':canPreorder?'PRE-ORDER · '+(v.price!=null?Number(v.price).toLocaleString('tr-TR')+' ₺':''):'ADD TO CART · '+(v.price!=null?Number(v.price).toLocaleString('tr-TR')+' ₺':'')}</button>}<a className="releaseBagLink" href="/store">BAG · {bagCount}</a></div></div>
}
