import Link from 'next/link';
import { releases } from './data/releases';
import './catalogue.css';

export default function Home() {
  return <main>
    <header className="nav shell"><a className="brand" href="#top" aria-label="Side II home"><img src="/brand/sideii-logo-flat.png" alt="Side II" /></a><nav><a href="#releases">Releases</a><a href="#imprints">Imprints</a><a href="#about">About</a><a href="#store">Store</a></nav></header>
    <section id="top" className="hero shell"><div className="sideWave" aria-hidden="true"><i/><i/><i/><i/><i/><i/><i/><i/><i/><i/><i/><i/><i/><i/><i/><i/><i/><i/></div><div className="heroCore"><div className="eyebrow">INDEPENDENT PHYSICAL MUSIC LABEL · EST. MMXXVI</div><div className="heroLogo"><img src="/brand/sideii-logo-silver.png" alt="Side II" /></div><p className="tagline">Music, in another form.</p></div><a className="scrollCue" href="#manifesto"><span>EXPLORE</span><b>↓</b></a><div className="heroFoot"><span>SELECTED RELEASES</span><span>CD · CASSETTE · LIMITED EDITIONS</span></div></section>
    <section id="manifesto" className="statement shell"><p>Sound becomes<br/>an <em>edition.</em></p><div><span>01 / APPROACH</span><p>Each Side:II release is developed as a complete physical edition: music, format, artwork and production considered together.</p><small>SOUND · ARTWORK · FORMAT</small></div></section>
    <section id="releases" className="section shell"><div className="sectionHead"><span>02 / CATALOGUE</span><h2>Selected<br/><i>releases.</i></h2></div><div className="releaseGrid">{releases.map(r=>{const content=<><div className="mediaStage"><div className="physicalMedia" aria-hidden="true"><i/></div><div className="cover">{r.cover?<img className="releaseArtwork" src={r.cover} alt={`${r.artist} — ${r.title}`} />:<><span>{r.catalogue}</span><b>{r.number}</b><img className="coverLogo" src="/brand/sideii-logo-flat.png" alt=""/><em>VIEW EDITION</em></>}</div></div><div className="releaseMeta"><span>{r.catalogue}</span><h3>{r.title}</h3><p>{r.artist} · {r.formatDetail}</p></div></>;return <Link className={`release ${r.media}`} href={`/releases/${r.slug}`} key={r.catalogue}>{content}</Link>})}</div><div className="catalogueFoot"><p className="forthcoming">First catalogue editions in production.</p><span>CATALOGUE / MMXXVI</span></div></section>
    <section id="imprints" className="imprint"><div className="shell imprintInner"><span>03 / IMPRINT</span><div className="imprintContent"><small className="imprintKicker">A SIDE:II IMPRINT</small><h2>Lethargia<br/><i>Records</i></h2><div className="imprintRule"/><p>Lethargia operates within Side:II with a distinct catalogue identity.<br/>Its visual system and physical formats are shaped release by release.</p><div className="imprintMeta"><small>SIDE:II / LETHARGIA</small><small>EST. MMXXVI</small></div><Link href="/lethargia" className="imprintExplore">OPEN LETHARGIA CATALOGUE →</Link></div></div></section>
    <section id="about" className="section about shell"><div className="sectionHead"><span>04 / ABOUT</span><h2>Built around<br/>the <i>release.</i></h2></div><div className="aboutCopy"><div className="aboutIndex">SIDE:II / INDEPENDENT / MMXXVI</div><p>Side:II develops physical music releases across compact disc, cassette and limited formats. The format and visual system are chosen for the individual project rather than imposed as a house style.</p><p>One release.<br/>One complete edition.</p><div className="formats"><span><b>01</b> CD</span><span><b>02</b> CASSETTE</span><span><b>03</b> LIMITED</span></div></div></section>
    <section id="store" className="storeWrap"><div className="store shell"><span>05 / STORE</span><div className="storeTitle"><h2>Catalogue editions<br/><em>coming into print.</em></h2><div className="storeMark">II</div></div><div className="storeRow"><div><p>Store access will begin as catalogue editions become available.</p><small>CD · CASSETTE · LIMITED EDITIONS</small></div><button disabled>STORE · COMING SOON</button></div></div></section>
    <section className="closing"><div className="shell closingInner"><span>06 / SIDE:II</span><p>Sound. Artwork.<br/><i>Physical edition.</i></p><a href="#top">RETURN TO TOP ↑</a></div></section>
    <footer><div className="shell footerInner"><div className="footerLogo"><img src="/brand/sideii-logo-flat.png" alt="Side II"/><small>INDEPENDENT PHYSICAL MUSIC LABEL</small></div><div className="footerNav"><a href="#top">TOP</a><a href="#releases">RELEASES</a><a href="#imprints">IMPRINTS</a><a href="#about">ABOUT</a><a href="#store">STORE</a></div><div className="footerMeta"><span>SIDE:II · EST. MMXXVI</span><span>CD · CASSETTE · LIMITED</span><span>© MMXXVI SIDE:II</span></div></div></footer>
  </main>;
}
