import Link from 'next/link';
import { releases } from './data/releases';

export default function Home() {
  return <main>
    <header className="nav shell"><a className="brand" href="#top" aria-label="Side II home"><img src="/brand/sideii-logo-flat.png" alt="Side II" /></a><nav><a href="#releases">Releases</a><a href="#imprints">Imprints</a><a href="#about">About</a><a href="#store">Store</a></nav></header>
    <section id="top" className="hero shell"><div className="sideWave" aria-hidden="true"><i/><i/><i/><i/><i/><i/><i/><i/><i/><i/><i/><i/><i/><i/><i/><i/><i/><i/></div><div className="heroCore"><div className="eyebrow">INDEPENDENT PHYSICAL MUSIC LABEL · EST. MMXXVI</div><div className="heroLogo"><img src="/brand/sideii-logo-silver.png" alt="Side II" /></div><p className="tagline">Music, in another form.</p></div><a className="scrollCue" href="#manifesto"><span>EXPLORE</span><b>↓</b></a><div className="heroFoot"><span>SELECTED RELEASES</span><span>CD · VINYL · CASSETTE · LIMITED EDITIONS</span></div></section>
    <section id="manifesto" className="statement shell"><p>Sound becomes<br/>an <em>edition.</em></p><div><span>01 / PHILOSOPHY</span><p>Side:II works with music in physical form. Format, artwork and production are developed around the identity of each release.</p><small>SOUND · ARTWORK · FORMAT</small></div></section>
    <section id="releases" className="section shell"><div className="sectionHead"><span>02 / CATALOGUE</span><h2>Selected<br/><i>releases.</i></h2></div><div className="releaseGrid">{releases.map(r=>{const content=<><div className="mediaStage"><div className="physicalMedia" aria-hidden="true"><i/></div><div className="cover">{r.cover?<img className="releaseArtwork" src={r.cover} alt={`${r.artist} — ${r.title}`} />:<><span>{r.catalogue}</span><b>{r.number}</b><img className="coverLogo" src="/brand/sideii-logo-flat.png" alt=""/><em>VIEW EDITION</em></>}</div></div><div className="releaseMeta"><span>{r.catalogue}</span><h3>{r.title}</h3><p>{r.artist} · {r.formatDetail}</p></div></>;return <Link className={`release ${r.media}`} href={`/releases/${r.slug}`} key={r.catalogue}>{content}</Link>})}</div><div className="catalogueFoot"><p className="forthcoming">First editions forthcoming.</p><span>CATALOGUE / MMXXVI</span></div></section>
    <section id="imprints" className="imprint"><div className="shell imprintInner"><span>03 / IMPRINT</span><div className="imprintContent"><small className="imprintKicker">A SIDE:II IMPRINT</small><h2>Lethargia<br/><i>Records</i></h2><div className="imprintRule"/><p>An independent imprint with its own visual and editorial language.<br/>Each physical edition is developed around the character of the release.</p><div className="imprintMeta"><small>CURATED BY SIDE:II</small><small>EST. MMXXVI</small></div><Link href="/lethargia" className="imprintExplore">EXPLORE LETHARGIA →</Link></div></div></section>
    <section id="about" className="section about shell"><div className="sectionHead"><span>04 / ABOUT</span><h2>Beyond<br/>the <i>format.</i></h2></div><div className="aboutCopy"><div className="aboutIndex">SIDE:II / INDEPENDENT / MMXXVI</div><p>Side:II is an independent label for physical music editions. We develop the format, artwork and presentation of each release as one coherent project — across compact disc, vinyl, cassette and limited editions.</p><p>The artist defines the work.<br/>The edition follows.</p><div className="formats"><span><b>01</b> CD</span><span><b>02</b> VINYL</span><span><b>03</b> CASSETTE</span><span><b>04</b> LIMITED</span></div></div></section>
    <section id="store" className="storeWrap"><div className="store shell"><span>05 / STORE</span><div className="storeTitle"><h2>First editions<br/><em>in production.</em></h2><div className="storeMark">II</div></div><div className="storeRow"><div><p>The Side:II store will open with the first catalogue releases.</p><small>VINYL · CD · CASSETTE · LIMITED EDITIONS</small></div><button disabled>STORE · COMING SOON</button></div></div></section>
    <section className="closing"><div className="shell closingInner"><span>06 / SIDE:II</span><p>Music considered<br/>in <i>physical form.</i></p><a href="#top">RETURN TO TOP ↑</a></div></section>
    <footer><div className="shell footerInner"><div className="footerLogo"><img src="/brand/sideii-logo-flat.png" alt="Side II"/><small>INDEPENDENT PHYSICAL MUSIC LABEL</small></div><div className="footerNav"><a href="#top">TOP</a><a href="#releases">RELEASES</a><a href="#imprints">IMPRINTS</a><a href="#about">ABOUT</a><a href="#store">STORE</a></div><div className="footerMeta"><span>INDEPENDENT PHYSICAL MUSIC LABEL</span><span>CD · VINYL · CASSETTE · LIMITED</span><span>© MMXXVI SIDE:II</span></div></div></footer>
  </main>;
}
